interval: 15m
log:
  debug: false
  type: text
  file:
    enable: false
    path: default.log
elasticsearch:
  host: http://localhost:9200
  ssl_certificate_verification: true
  auth:
    enable: false
    username: elastic
    password: secret
  indices:
  - name: '*'
    rollover_pattern: '[0-9]{4}.[0-9]{2}.[0-9]{2}'
kibana:
  host: http://localhost:5601
  ssl_certificate_verification: true
  auth:
    enable: false
    username: elastic
    password: secret
xpack:
  enable: false
  spaces:
  - name: global
    pattern: '*'
    timestamp: timestamp
opendistro:
  enable: false
  tenants:
  - name: global
    pattern: '*'
    timestamp: timestamp
