elasticsearch: 
  host: http://elasticsearch.local
  indexPattern: "log-"
  auth: false
  user: username
  password: secret
kibana: 
  host: http://kibana.local
  maxPage: 1000
  auth: false
  user: username
  password: secret
interval: 15